version: '3.1'

services:

  nginx:
    image: emcniece/nginx-cache-purge:1.13-alpine
    ports:
      - 8080:80
    links:
      - wp-fpm
    volumes:
      - ./wp-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wproot:/var/www/html

  wp-fpm:
    tty: true
    stdin_open: true
    image: emcniece/wordpress:4-php7.1-fpm-alpine
    volumes:
      - wproot:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  mysql:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress

  redis:
    image: redis:3-alpine

volumes:
  wproot: